version: 1
disable_existing_loggers: false

formatters:
  console:
    (): structlog.dev.ConsoleRenderer
    colors: true
    exception_formatter: structlog.dev.DefaultExceptionFormatter
  json:
    (): structlog.processors.JSONRenderer

handlers:
  console:
    class: logging.StreamHandler
    formatter: console
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: logs/cloud-drift.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

root:
  level: DEBUG
  handlers: [console, file]

loggers:
  cloud_drift_analyzer:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  cloud_drift_analyzer.providers:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  cloud_drift_analyzer.state_adapters:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  botocore:
    level: WARNING
    handlers: [console]
    propagate: false

  urllib3:
    level: WARNING
    handlers: [console]
    propagate: false

processors:
  - structlog.processors.add_log_level
  - structlog.processors.TimeStamper(fmt="iso")
  - structlog.processors.StackInfoRenderer
  - structlog.processors.format_exc_info
  - structlog.processors.UnicodeDecoder
  - structlog.processors.ExceptionPrettyPrinter